name: Build and Deploy HTML Project to GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

     
      - name: Install dependencies
        run: npm install

     
      - name: Build HTML Project
        run: echo "No build step needed for static HTML project"  
  deploy:
    runs-on: ubuntu-latest
    needs: build  

    steps:
   
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "lalashabir"
          git config --global user.email "lalashabir529@gmail.com"

    
      - name: Install gh-pages
        run: npm install gh-pages --save-dev

    
      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  
        run: |
          # Set up authentication using the GitHub token
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/your-username/practice.git
          # Deploy the content to GitHub Pages
          npx gh-pages -d . -r https://github.com/your-username/practice.git -b gh-pages
